# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-23 18:59
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritiesAvail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('symbol', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_rec_fg',
                 models.BooleanField(default=True, help_text='Set to True for the current version of the record',
                                     verbose_name='Current record flag')),
                ('effective_dt', models.DateTimeField(default=django.utils.timezone.now,
                                                      help_text='The date & time on which this record became active',
                                                      verbose_name='Record effective date')),
                ('end_dt',
                 models.DateTimeField(blank=True, help_text='The date and time on which this record expired', null=True,
                                      verbose_name='Record end date')),
            ],
        ),
    ]
