# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-27 16:45
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('balancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAvailStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_rec_fg',
                 models.BooleanField(default=True, help_text='Set to True for the current version of the record',
                                     verbose_name='Current record flag')),
                ('effective_dt', models.DateTimeField(default=django.utils.timezone.now,
                                                      help_text='The date & time on which this record became active',
                                                      verbose_name='Record effective date')),
                ('end_dt',
                 models.DateTimeField(blank=True, help_text='The date and time on which this record expired', null=True,
                                      verbose_name='Record end date')),
            ],
        ),
        migrations.AddField(
            model_name='securityavail',
            name='at_dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 27, 16, 45, 27, 541377),
                                       verbose_name='Price Date & Time'),
        ),
        migrations.AddField(
            model_name='securityavail',
            name='security_avail_static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='balancer.SecurityAvailStatic'),
        ),
    ]
