# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-23 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('balancer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='curr_rec_fg',
        ),
        migrations.RemoveField(
            model_name='security',
            name='end_dt',
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='curr_rec_fg',
        ),
        migrations.RemoveField(
            model_name='securityprice',
            name='end_dt',
        ),
    ]
