# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-23 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('balancer', '0002_auto_20170923_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='symbol',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([('security', 'at_dt')]),
        ),
    ]
