# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-24 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('balancer', '0003_auto_20170923_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='effective_dt',
            field=models.DateTimeField(auto_now=True, help_text='The date & time on which this record became active',
                                       verbose_name='Record effective date'),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='at_dt',
            field=models.DateField(auto_now_add=True, verbose_name='Price Date'),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='effective_dt',
            field=models.DateTimeField(auto_now=True, help_text='The date & time on which this record became active',
                                       verbose_name='Record effective date'),
        ),
    ]
