# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('balancer', '0004_auto_20170924_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityprice',
            old_name='at_dt',
            new_name='price_dt',
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set([('security', 'price_dt')]),
        ),
    ]
