# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-14 14:42
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('balancer', '0008_auto_20171012_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Account Number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Close Date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Open Date',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='As Of',
        ),
        migrations.AddField(
            model_name='account',
            name='acct_num',
            field=models.TextField(blank=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='account',
            name='close_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Close Date'),
        ),
        migrations.AddField(
            model_name='account',
            name='open_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Open Date'),
        ),
        migrations.AddField(
            model_name='holding',
            name='as_of_dt',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='As Of'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='balancer.Account'),
        ),
    ]
