# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-14 19:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('balancer', '0009_auto_20171014_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='balancer.Account'),
        ),
    ]
