# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-02 02:37
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('balancer', '0011_auto_20171015_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('percent', models.PositiveSmallIntegerField(help_text='Percent of portfolio in this category',
                                                             validators=[
                                                                 django.core.validators.MaxValueValidator(100)])),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancer.Security')),
            ],
        ),
        migrations.AlterField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='balancer.Account'),
        ),
    ]
